# Generated by Django 6.0.2 on 2026-02-21 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArtifactCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("yeti", "Yeti"),
                            ("ghosts", "Ghosts"),
                            ("aliens", "Aliens"),
                            ("vampires", "Vampires"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MapPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("latitude", models.DecimalField(decimal_places=12, max_digits=20)),
                ("longitude", models.DecimalField(decimal_places=12, max_digits=20)),
                ("username", models.CharField(max_length=255)),
                ("user_id", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maps.artifactcategory",
                    ),
                ),
            ],
        ),
    ]
