# Generated by Django 6.0.2 on 2026-02-21 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mappoint",
            name="username",
        ),
    ]
