# Generated by Django 6.0.2 on 2026-02-21 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0002_remove_mappoint_username"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="mappoint",
            unique_together={("latitude", "longitude")},
        ),
    ]
