# Generated by Django 6.0.2 on 2026-02-21 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0003_alter_mappoint_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="mappoint",
            unique_together=set(),
        ),
    ]
