# Generated by Django 6.0.2 on 2026-02-24 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0004_alter_mappoint_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mappoint",
            old_name="user_id",
            new_name="author_id",
        ),
        migrations.RenameField(
            model_name="mappoint",
            old_name="name",
            new_name="label",
        ),
        migrations.RemoveField(
            model_name="mappoint",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="mappoint",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="mappoint",
            name="longitude",
        ),
        migrations.AddField(
            model_name="mappoint",
            name="lat",
            field=models.DecimalField(decimal_places=18, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name="mappoint",
            name="lng",
            field=models.DecimalField(decimal_places=18, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="artifactcategory",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
