# Generated by Django 6.0.2 on 2026-03-03 14:29

import django.db.models.deletion
import maps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_rename_user_id_mappoint_author_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappoint',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mappoint',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=maps.models.marker_image_path),
        ),
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.IntegerField()),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='maps.mappoint')),
            ],
            options={
                'unique_together': {('marker', 'author_id')},
            },
        ),
    ]
